language: rust
cache: cargo
rust:
  - nightly-2019-04-26

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
  - cargo test
