max_width = 90

## unstable features are only available in nightly channel ##
#############################################################
# comment_width = 90
# wrap_comments = true
# format_strings = false
# trailing_semicolon = true
